# Generated by Django 4.2.3 on 2023-07-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_small_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='small_description',
            field=models.CharField(default='Default description', max_length=150),
        ),
    ]
