# Generated by Django 4.2.3 on 2023-08-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
